### ISSUE TITLE
Project structure?

### ISSUE THREAD

**Issue by boroicamarius** [AOSXAP/AndroidMan#5]
Is this way of organizing files ok for you?
https://www.youtube.com/watch?v=2-xga0a0T2Q

**Comment by andreipiscoran** [comment]
![Screenshot_2024-03-20-11-30-38-424_com google android youtube-edit](https://github.com/AOSXAP/AndroidMan/assets/74103250/f89809eb-c790-4a9d-aa11-8fe042d54a59)

We will use this structure.
